apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: k8s-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30002
  type: NodePort
