apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: dGVzdHVzZXI=  # testuser (Base64 encoded)
  password: dGVzdHBhc3N3b3Jk  # testpassword (Base64 encoded)
